### ISSUE TITLE
Manually added line breaks are removed

### ISSUE THREAD

**Issue by deathaxe** [btrekkie/WrapAsYouType#2]
If a line break is inserted by manually pressing the `enter` key a user most likely wants that break. Hence removing it automatically may not be desirable. 

![animation](https://user-images.githubusercontent.com/16542113/48970745-4bffd300-f010-11e8-9271-4ae4f03d7e39.gif)

**Comment by dhelonious** [comment]
Line breaks are removed in the same manner if some consecutive lines are commented out separately.

**Comment by btrekkie** [comment]
@dhelonious: That seems like a separate problem.  Would you mind creating another issue for that?

Yes, it seems like preserving the line break would be better for user experience.  @deathaxe, perhaps you could offer feedback on some of the details?

* I'm thinking WrapAsYouType should remember and preserve the most recent enter press, until the user edits away from it.  (Something like this: if the `EventListener` receives a call to `on_selection_modified` without an accompanying call to `on_modified`, then forget the line break.  Also, keep track of the newline's position by marking it with an invisible region using `View.add_regions`.)  This will be helpful in the case of normal, forward editing, and it seems straightforward.  However, later edits could induce WrapAsYouType to delete the line break, if the user goes back and edits the paragraph before the line break, or he goes back and edits the first line of the paragraph after the line break.

* Alternatively, WrapAsYouType could remember and preserve all enter presses.  However, I don't see how to do this efficiently.  Presumably, it would need to keep track of the regions using `View.add_regions` and `View.get_regions`, but these methods (probably) take an amount of time proportional to the total number of saved line breaks.  This might be okay in practice, but it seems bad in theory, and WrapAsYouType needs to be fast since it operates on every keystroke.
  
  The user would still lose all of the saved enter presses if he closed and reopened a document.  There's no foolproof way to preserve all of the user's line breaks.  The `"wrap_as_you_type_paragraphs"` setting is currently the only way to permanently preserve paragraph breaks that cannot be inferred from indentation.  Still, it seems valuable to make some effort to respect the user's wishes when he presses the enter key.

* It seems like the best way to detect an enter-press-like event is to check for an "insert" command that inserts at least one newline character (e.g. `{"characters": "\n"}`).  Unfortunately, the Sublime 2 API doesn't have `EventListener.on_text_command`, so it looks like I'll have to use `View.command_history` to detect this.

Anyway, sorry for the long comment, I'm just thinking out loud.

**Comment by dhelonious** [comment]
@btrekkie Despite your fix, unfortunately, this issue still occurs for me (Sublime Text 3, Build 3176).

**Comment by btrekkie** [comment]
When this issue occurs, are you moving the selection cursor (or performing an undo command) between pressing the enter key and when it misbehaves?  If so, then that explains it.  (I'm not saying this behavior is necessarily ideal, only that I can explain it.)

I implemented the approach described in the first bullet point of my comment <https://github.com/btrekkie/WrapAsYouType/issues/2#issuecomment-441764018>.  The thinking behind forgetting any explicit line breaks when the user moves the cursor was that this seems like more straightforward, "local" behavior.  It would seem a little weird to me if the user pressed enter, then heavily edited a different part of the document, and then came back and WrapAsYouType continued preserving that one enter press from a long time ago.

But maybe this approach was not ideal.  Do you have any suggestions?

**Comment by deathaxe** [comment]
I guess this issue might be triggered by other plugins like Doxygen/Docblocker moving the cursor. A new line in an indented python docstring is still moved to the previous one.

I thought about your suggestions from above and got an idea of the dilemma. I guess there is no optimal solution to decide when to wrap and when not as there is nothing which indicates a desired or automatic line break. In M. Word you can enter different characters, telling Word about the type, but this is not possible in a text editor. You'd always need an empty line as delimiter, but this makes only sense in markdown and co. which do not need hard word wrapping.

**Comment by dhelonious** [comment]
I already read through the commit log and see that there are situations, in which line breaks are removed (thats the reason why I opened issue #5). I do not move the cursor or anything that could explain this issue with desired behavior. Basically, I did the same as in the gif above: comment, type something, line break, comment, type something.

As @deathaxe said, I also suspected that some packages I have installed are the reasons for this issue. After some testing I identified 3 packages which are responsible:

- [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter)
- [Case Conversion](https://packagecontrol.io/packages/Case%20Conversion)
- [DocBlockr](https://packagecontrol.io/packages/DocBlockr)

All of these packages are rather important for me. Except for DocBlockr, I have no idea, why these packages break the desired behavior of your plugin. 😕

**Comment by btrekkie** [comment]
@dhelonious, thanks for investigating!  I tested out the plugins you identified, along with DoxyDoxygen, which @deathaxe mentioned.  Here's what I found:

DocBlockr: WrapAsYouType fails to detect enter press events, because pressing enter with DocBlockr installed triggers an "insert_snippet" command rather than an "insert" command.  This should be easy to fix.

DoxyDoxygen: WrapAsYouType fails to detect enter press events, because pressing enter with DoxyDoxygen installed triggers a "doxy_enter" command rather than an "insert" command.  I'm not sure what to do here, short of getting into the business of whitelisting command names from random plugins.

Case Conversion: I was unable to reproduce the problem with Case Conversion installed.

BracketHighlighter: I have tracked the issue to a bug in Sublime.  For a minimal example illustrating the bug, add the following code to any Sublime plugin:

```python
import sublime

class BreakWrapAsYouType(sublime_plugin.EventListener):
    def on_selection_modified(self, view):
        def break_wrap_as_you_type():
            view.settings().set('foo', True)
            view.settings().set('foo', False)
        sublime.set_timeout(break_wrap_as_you_type, 0)
```

This has the effect of clearing the `'wrap_as_you_type_explicit_line_break'` region sometimes, which breaks enter preserving.

I'm reopening this issue because the DocBlockr problem is fixable.

**Comment by dhelonious** [comment]
@btrekkie Thank you for the effort. I checked again and Case Conversion definitely does not cause any issues.

Any chance, that there is a workaround for the bug in Sublime Text to preserve line breaks?

**Comment by btrekkie** [comment]
@dhelonious Off the top of my head, the only workaround I can think of is to keep track of the explicit line break manually, i.e. by storing its position in a variable.  However, this wouldn't work in all cases.  If the user runs a custom text command that, say, adds text before the explicit line break, then the stored position of the line break would no longer be correct.

I imagine that there's a way to alter BracketHighlighter to work around the bug, but that approach seems backwards to me.

**Comment by dhelonious** [comment]
@btrekkie I see, this is no solution for the issue. I think a fix in BracketHighlighter, if easily possible, would be nice. However, I do not fully understand what is causing this bug. Is it the specific combination of `on_selection_modified`, `set_timeout` and `set`?

**Comment by btrekkie** [comment]
@dhelonious I don't get what causes the bug either.  I think randomly messing with BracketHighlighter's code could fix the issue.  For example, changing "bracket_highlighter.busy" from a setting to a variable should fix it.  That setting is only read in one place anyway.  Maybe storing the `Settings` object in a variable rather than calling `View.settings()` each time would make a difference.  You could also try using a delay of 1 millisecond rather than 0 milliseconds, or changing `BhListenerCommand` to override `on_selection_modified_async` instead of `on_selection_modified` (although that seems like a bigger change).

Now that I think about it, plugins other than WrapAsYouType would also benefit from a workaround, if they use regions as well.

**Comment by dhelonious** [comment]
@btrekkie That is indeed strange. I think I will open an issue for BracketHighlighter if I have the time. Thanks anyway!
