### ISSUE TITLE
Lines are joined on removing line breaks

### ISSUE THREAD

**Issue by dhelonious** [btrekkie/WrapAsYouType#4]
In Markdown I set up the plugin to wrap the entire document. When a line break is removed, however, the previous two lines are joined (see below). If this is undone, first the unintentionally removed line break appears and afterwards the intentionally removed line break.

![wrapasyoutype](https://user-images.githubusercontent.com/6987220/49065626-d7e74a00-f21e-11e8-91d6-2513f6dc6a05.gif)

**Comment by btrekkie** [comment]
Thanks for creating the issue.  I would describe this as intended behavior: WrapAsYouType was asked to wrap the entire document, and that's what it's doing.  (The reason that the wrapping occurs when deleting the line break is that word wrap fixup operates locally: if the current line cannot be wrapped with the previous line or the next line, then nothing happens.)

If you're using Sublime 3, might I suggest changing your `"wrap_as_you_type_sections"` setting to something like this?

```json
{
    "wrap_as_you_type_sections": [
        {
            "selector": "meta.paragraph - markup.raw"
        }
    ]
}
```

Sublime 2 is a bit trickier, because the built-in syntax file for Markdown does not give a lot of scope information.  In that case, maybe you could find a better syntax file.

Incidentally, I'm sure further improvements could be made to this setting, but I haven't used Markdown enough to work them out.  If by any chance you use Markdown a lot and end up tweaking the setting some more, feel free to send me your improved setting (as a comment or a pull request) so I can add it to `README.md` as an example.  See https://github.com/btrekkie/WrapAsYouType#wrap_as_you_type_sections for an explanation of the `"wrap_as_you_type_sections"` setting.

**Comment by dhelonious** [comment]
Thank you for the fast reply. You're right, I did not notice that this behavior is indeed intended inside a paragraph. Fortunately I use Sublime Text 3, so your suggestion works perfectly fine. I don't use Markdown a lot myself, however, if I find find some useful config I will gladly message you.

I really like your plugin and it replaced AutoWrap for me, especially after [b080eed](https://github.com/btrekkie/WrapAsYouType/commit/b080eedb245d86c7c46d2325e74c6f8befbc5d90). 👍
